### ISSUE TITLE
Dúvidas relacionadas a Análise de Requisitos

### ISSUE THREAD

**Issue by reebr** [CodeSolidario/adoteUmPet#5]
Lendo a análise de requisitos, me surgiu algumas dúvidas.

1. Linguagem do back-end
Existe a necessidade de trabalhar o back-end em alguma linguagem específica?

2. Manter Usuário
O que seria o campo `status` relacionado ao usuário? Quais status este poderia ter?

3. Anúncios
Usuários também poderão criar anúncios ou essa opção estará restrita somente às instituições?

4. Mensagens
O envio de mensagens deve ser disponível somente para usuários registrados na aplicação ou qualquer pessoa (um visitante, por exemplo) poderá enviar mensagens para a instituição?

**Comment by thedannyreis** [comment]
Olá, desculpe a demora em responder mas este projeto ficou parado por um tempo por falta de tempo, estou tentando retomar agora e vou refazer toda a estrutura, peço que acompanhe e caso possa ajudar em algo será muito bom. Obrigada!

**Comment by reebr** [comment]
Beleza, estou por aqui. 🤝 

Vou fechar essa issue pois era ela baseada na análise de requisitos anterior, que estava no repositório.
